using UnityEngine;
using GuidedFury.Core.Atmosphere;
using GuidedFury.Core.Missile;
using GuidedFury.Core.State;

namespace GuidedFury.Core.Integrators
{
    /// <summary>
    /// LOD 3 — Pseudo-6DOF. Full rigid-body orientation; body axis can diverge from velocity.
    ///
    /// **The big leap from L0/L1/L2:** at all those tiers, orientation snapped to velocity
    /// each step. At L3, orientation is its own state that evolves via angular velocity.
    /// This unlocks the realistic visual and physical behaviors a missile actually shows:
    /// - Angle of attack (AoA) — body axis pitched relative to motion vector.
    /// - Lift force generated by that AoA, perpendicular to velocity.
    /// - Thrust acting along the body's long axis, not along velocity (so a pitched-up
    ///   missile under thrust actually pulls upward).
    /// - Weather-vane stability — passive aerodynamic moment that drives AoA back to zero.
    ///   Real airframes do this from the same physics that generates lift; we model it as a
    ///   separate restoring moment for cleaner tuning.
    /// - Inner-loop autopilot — converting "lateral accel command" from guidance into a
    ///   commanded body rotation rate, then applying torque to track it.
    ///
    /// **The autopilot lives inline here** (not extracted as a separate `IAutopilot`
    /// interface yet). It's a simple proportional rate controller — it computes the rate
    /// that *would* produce the commanded accel given current speed (ω = a / v), then
    /// applies torque proportional to (ω_command − ω_current). L4 will extract this so
    /// multiple autopilot strategies can be plugged in.
    ///
    /// **What L3 still doesn't model (vs. L4):**
    /// - Aerodynamic coefficient tables (Cd, Cl, Cm as functions of Mach + α + δ). At L3,
    ///   Cl is a scalar with linear-then-stall behaviour; Cd is the same single value as L1.
    /// - Control surface deflections — L3 applies torque directly via the autopilot,
    ///   pretending the airframe has perfect attitude control internally.
    /// - Cross-coupling between roll / pitch / yaw moments. We treat them as independent.
    ///
    /// **Integration scheme:** forward Euler for translation and angular velocity;
    /// quaternion derivative (q̇ = ½·q·ω) for orientation. Short flight times mean Euler
    /// energy drift is bounded. L4 may go to semi-implicit or RK4 for sharper aero forces.
    /// </summary>
    public sealed class PseudoRb6DofL3Integrator : IPhysicsIntegrator
    {
        public MissileLod Lod => MissileLod.L3_PseudoRb6Dof;

        private const float Gravity = 9.80665f;

        public void Initialize(in MissileProfileData profile, ref MissileState state)
        {
            state.Mass = profile.DryMassKg + profile.PropellantMassKg;
            state.Fuel = profile.PropellantMassKg;

            // Launch velocity along the body forward axis at cruise speed (mirrors L1/L2).
            Vector3 forward = state.Orientation * Vector3.forward;
            state.Velocity = forward * profile.CruiseSpeedMps;

            // L3 starts with zero body angular velocity. The autopilot brings it to whatever
            // the guidance command requires.
            state.AngularVelocity = Vector3.zero;

            state.Phase = MissilePhase.Boost;
        }

        public void Step(
            in MissileProfileData profile,
            in MissileCommand command,
            in AtmosphereSample atmo,
            float dt,
            ref MissileState state)
        {
            // -- Phase advance and mass burn ----------------------------------
            bool boosting = state.Phase == MissilePhase.Boost && state.TimeOfFlight < profile.BoostDurationS;
            if (state.Phase == MissilePhase.Boost && !boosting)
            {
                state.Phase = MissilePhase.Cruise;
                state.Fuel  = 0f;
                state.Mass  = profile.DryMassKg;
            }

            // -- Body-frame setup ----------------------------------------------
            // Pre-compute basis vectors so we can decompose forces and torques cleanly.
            Vector3 bodyForward = state.Orientation * Vector3.forward;
            Vector3 bodyRight   = state.Orientation * Vector3.right;
            Vector3 bodyUp      = state.Orientation * Vector3.up;

            float speedSq = state.Velocity.sqrMagnitude;
            float speed   = speedSq > 1e-6f ? Mathf.Sqrt(speedSq) : 0f;
            Vector3 velocityDir = speed > 1e-6f ? state.Velocity / speed : bodyForward;

            // -- Angle of attack ----------------------------------------------
            // α is the angle between body forward and velocity. Sign / axis encoded by the
            // cross product so we can decompose AoA into pitch and yaw components later.
            // At zero speed we just say AoA = 0 (well-defined; nothing to be off-axis from).
            float aoaRad = 0f;
            Vector3 aoaAxis = Vector3.zero; // axis perpendicular to both bodyForward and velocity
            if (speed > 0.1f)
            {
                float cosAoa = Mathf.Clamp(Vector3.Dot(bodyForward, velocityDir), -1f, 1f);
                aoaRad = Mathf.Acos(cosAoa);

                // Axis: bodyForward × velocityDir gives the rotation axis from body to velocity.
                Vector3 cross = Vector3.Cross(bodyForward, velocityDir);
                if (cross.sqrMagnitude > 1e-8f)
                    aoaAxis = cross.normalized;
            }

            // Dynamic pressure — appears in every aero force.
            float dynamicPressure = 0.5f * atmo.Density * speedSq;

            // -- Force accumulation -------------------------------------------
            Vector3 totalForce = Vector3.zero;

            // Gravity.
            totalForce += Vector3.down * (state.Mass * Gravity);

            // Drag along velocity (same model as L1).
            if (speed > 1e-3f && profile.DragCoefficient > 0f && profile.ReferenceAreaM2 > 0f)
            {
                float dragMagnitude = dynamicPressure * profile.DragCoefficient * profile.ReferenceAreaM2;
                totalForce += -velocityDir * dragMagnitude;
            }

            // Lift from AoA. Direction: perpendicular to velocity, in the plane of (body, velocity),
            // pointing from velocity toward body forward (so a pitched-up missile gets lifted up).
            if (speed > 1e-3f && profile.LiftSlopePerRad > 0f && profile.ReferenceAreaM2 > 0f && aoaRad > 1e-4f)
            {
                // Linear region: Cl = Cl_α · α. Past stall: linearly decreasing to zero at 2·α_stall.
                float stallRad = profile.StallAoaDeg * Mathf.Deg2Rad;
                float liftCl;
                if (aoaRad <= stallRad)
                {
                    liftCl = profile.LiftSlopePerRad * aoaRad;
                }
                else if (aoaRad <= 2f * stallRad)
                {
                    // Linear decay from Cl_max to 0 across the post-stall region.
                    float clMax = profile.LiftSlopePerRad * stallRad;
                    liftCl = clMax * (1f - (aoaRad - stallRad) / stallRad);
                }
                else
                {
                    liftCl = 0f;
                }

                // Lift direction: aoaAxis × velocityDir gives a vector perpendicular to velocity
                // in the (body, velocity) plane, pointing toward body forward. (Right-hand rule:
                // aoaAxis is perpendicular to both; crossing it with velocity gives lift dir.)
                Vector3 liftDir = Vector3.Cross(aoaAxis, velocityDir).normalized;

                float liftMagnitude = dynamicPressure * liftCl * profile.ReferenceAreaM2;
                totalForce += liftDir * liftMagnitude;
            }

            // Thrust during boost — ALONG BODY AXIS, not velocity. This is the defining
            // L3 behavior: a pitched-up boosting missile accelerates along its own nose
            // rather than along its velocity vector.
            if (boosting)
                totalForce += bodyForward * profile.BoostThrustN;

            // Convert to acceleration.
            float invMass = state.Mass > 1e-3f ? 1f / state.Mass : 0f;
            Vector3 accel = totalForce * invMass;

            // -- Autopilot: lateral-accel command → commanded body rate -------
            // Guidance produces a commanded lateral accel (m/s²). We want to convert that
            // into a body rotation rate that, applied to the velocity vector, would produce
            // that accel: ω = a_lat / v.
            //
            // The rotation should happen perpendicular to BOTH the commanded accel direction
            // AND the velocity. Specifically: ω = (velocity × a_command) / v² is the standard
            // identity (analogous to the LOS rate calculation in ProNav).
            //
            // The autopilot then applies torque proportional to (ω_command − ω_current),
            // tracking the commanded body rate with first-order dynamics.
            Vector3 commandedBodyRate = Vector3.zero;
            Vector3 aCommand = command.CommandedAccelerationWorld;
            if (speed > 1.0f && aCommand.sqrMagnitude > 1e-6f)
                commandedBodyRate = Vector3.Cross(state.Velocity, aCommand) / speedSq;

            // Rate-error torque. Applied in world frame; we'll transform to body frame for
            // the angular-velocity integration step.
            Vector3 rateErrorWorld = commandedBodyRate - WorldFromBodyAngularVel(state.Orientation, state.AngularVelocity);
            Vector3 controlTorqueWorld = rateErrorWorld * (profile.AutopilotGain * state.Mass);
            // Note: scaling by mass is a convenience so AutopilotGain ends up having
            // reasonable units. Real implementations scale by inertia.

            // -- Weather-vane (passive aero restoring moment) -----------------
            // The airframe naturally aligns with velocity over time. Magnitude scales with
            // AoA and dynamic pressure. Direction: about the aoaAxis (which rotates body
            // forward toward velocity).
            Vector3 weatherVaneTorqueWorld = Vector3.zero;
            if (aoaRad > 1e-4f && profile.WeatherVaneCoefficient > 0f && dynamicPressure > 0f)
            {
                float magnitude = profile.WeatherVaneCoefficient * dynamicPressure * profile.ReferenceAreaM2 * aoaRad;
                weatherVaneTorqueWorld = aoaAxis * magnitude;
            }

            Vector3 totalTorqueWorld = controlTorqueWorld + weatherVaneTorqueWorld;

            // -- Angular velocity update -------------------------------------
            // Decompose total torque into body frame and apply inertia (axisymmetric).
            // For axisymmetric body: I_yy = I_zz = TransverseInertia; I_xx = RollInertia.
            // Convention in this sim: Z = body forward (long axis = roll axis).
            Vector3 torqueBody = Quaternion.Inverse(state.Orientation) * totalTorqueWorld;
            Vector3 angAccelBody = new Vector3(
                torqueBody.x / profile.TransverseInertiaKgM2, // pitch about body X
                torqueBody.y / profile.TransverseInertiaKgM2, // yaw   about body Y
                torqueBody.z / profile.RollInertiaKgM2        // roll  about body Z
            );
            state.AngularVelocity += angAccelBody * dt;

            // -- Orientation update via quaternion derivative -----------------
            // q̇ = ½ · ω_q · q,  where ω_q = (ωx, ωy, ωz, 0) is the body-rate quaternion.
            // Forward Euler: q_new = q + q̇ · dt, then renormalise.
            Vector3 omegaBody = state.AngularVelocity;
            Quaternion omegaQuat = new Quaternion(omegaBody.x, omegaBody.y, omegaBody.z, 0f);
            Quaternion dq = QuatScale(QuatMul(state.Orientation, omegaQuat), 0.5f * dt);
            state.Orientation = QuatNormalize(QuatAdd(state.Orientation, dq));

            // -- Linear state integration -------------------------------------
            state.Velocity += accel * dt;
            state.Position += state.Velocity * dt;

            // -- Mass burn ----------------------------------------------------
            if (boosting && profile.BoostDurationS > 1e-6f)
            {
                float burnRate = profile.PropellantMassKg / profile.BoostDurationS;
                state.Fuel = Mathf.Max(0f, state.Fuel - burnRate * dt);
                state.Mass = profile.DryMassKg + state.Fuel;
            }

            // -- Time bookkeeping and lifetime guard --------------------------
            state.TimeOfFlight += dt;
            if (state.TimeOfFlight >= profile.MaxLifetimeS)
                state.Phase = MissilePhase.Failed;
        }

        // ===========================================================================
        // Quaternion helpers
        // ===========================================================================
        // Unity's Quaternion doesn't provide arithmetic — these implement the algebra we
        // need for q̇ = ½ q ω integration. Kept private and inline; if more integrators
        // need them, they get hoisted into a shared MathHelpers class.

        private static Quaternion QuatMul(Quaternion a, Quaternion b)
        {
            // Hamilton product, Unity convention (xyzw).
            return new Quaternion(
                a.w * b.x + a.x * b.w + a.y * b.z - a.z * b.y,
                a.w * b.y - a.x * b.z + a.y * b.w + a.z * b.x,
                a.w * b.z + a.x * b.y - a.y * b.x + a.z * b.w,
                a.w * b.w - a.x * b.x - a.y * b.y - a.z * b.z
            );
        }

        private static Quaternion QuatScale(Quaternion q, float s)
        {
            return new Quaternion(q.x * s, q.y * s, q.z * s, q.w * s);
        }

        private static Quaternion QuatAdd(Quaternion a, Quaternion b)
        {
            return new Quaternion(a.x + b.x, a.y + b.y, a.z + b.z, a.w + b.w);
        }

        private static Quaternion QuatNormalize(Quaternion q)
        {
            float magSq = q.x * q.x + q.y * q.y + q.z * q.z + q.w * q.w;
            if (magSq < 1e-12f) return Quaternion.identity;
            float invMag = 1f / Mathf.Sqrt(magSq);
            return new Quaternion(q.x * invMag, q.y * invMag, q.z * invMag, q.w * invMag);
        }

        /// <summary>
        /// Transform a body-frame angular velocity to world frame. Body angular velocity is
        /// stored in the state; world frame is what we compare against guidance's commanded
        /// rate (also in world frame).
        /// </summary>
        private static Vector3 WorldFromBodyAngularVel(Quaternion orientation, Vector3 omegaBody)
        {
            return orientation * omegaBody;
        }
    }
}
